### PR TITLE
Add brazilian portuguese locale file

### PR DESCRIPTION
**Pull request by lucastx**
Adds `pt-br.json`, containing a complete (as of v1.1.0) translation of
strings provided at `en.json`.

This enables a translated interface of RAWRR once built or served with `module.exports.pluginOptions.i18n.locale` changed to `pt-br` in `vue.config.js`.

### CODE REVIEW

**Comment by Alekxanderz** [comment]
Hello @lucastx ! 

Thank you so much for contributing to RAWRR!. I'll be accepting your request and merging it into the main branch. 

Additionally, I wanted to let you know that we're about to drop in the next couple of days a feature that easily allows switching languages without having to manually modify the locales before building or serving. I'll make sure to include the translation you provided.

**Comment by lucastx** [comment]
Thank you @Alekxanderz! It was a pleasure to contribute! I was actually midway into opening an issue to discuss ways to make the localization more accessible for users, I've seen somewhere I can't find now that you were planning on releasing a spanish localization :-) good to know it's actually about to appear!

I'll seize the opportunity of another build coming to present a second pull request that may be useful.

**Comment by lucastx** [comment]
Also, please tell me if there are any new strings in this reestructuring (such as the categories of entries) which are lacking for the feature drop so I can translate those too.

Thanks again for developing this, really appreciated!

**Comment by Alekxanderz** [comment]
Hello @lucastx !

We released the feature a couple of days ago, and I have just now published a branch (feature/brazilianPortuguese) for integrating the translation you provided. Please give it a look and let us know if everything is appropriate and working as intended. (make sure to delete old db files just in case to avoid compatibility issues)

We didn't add new strings, but I noticed that there are two untranslated ones in the pt-br locale file, the keys are:

- add_all (`"add_all": "Add all"`)
- test_success `("test_success": "Test values loaded successfully")`

Could you please provide translations for those as well? We'd really appreciate it!

**Pull request merged**
